apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "augmend-app.fullname" . }}
  labels:
{{ include "augmend-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "augmend-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "augmend-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "augmend-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}          
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key:  privateKey
                  name: credentials
            - name: GITHUB_APP_IDENTIFIER
              valueFrom:
                secretKeyRef:
                  key:  appId
                  name: credentials
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key:  webhookSecret
                  name: credentials
            - name: SSL_CERT
              valueFrom:
                secretKeyRef:
                  key:  sslCert
                  name: credentials
            - name: SSL_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key:  sslKey
                  name: credentials
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
