apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  privateKey: {{ .Values.privateKey | b64enc }}
  appId: {{ .Values.appId | b64enc }}
  webhookSecret: {{ .Values.webhookSecret | b64enc }}