apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  privateKey: {{ .Values.privateKey | b64enc }}
  appId: {{ .Values.appId | b64enc }}
  webhookSecret: {{ .Values.webhookSecret | b64enc }}
  sslCert: {{ .Values.sslCert | b64enc }}
  sslKey: {{ .Values.sslKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: augmend-tls
data:
  tls.crt: "{{ .Values.ingress.tls.sslCertPath | .Files.Get | trimSuffix "\n" |  b64enc }}"
  tls.key: "{{ .Values.ingress.tls.sslCertKey | .Files.Get | trimSuffix "\n" | b64enc }}"
type: kubernetes.io/tls
